title: nOps Documentation site
description: learn how to get the most value out of nOps
theme: just-the-docs

remote_theme: just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
  collections: true

# pmarsceill/just-the-docs